### ISSUE TITLE
MMPopupView isn't shown up

### ISSUE THREAD

**Issue by bitnpc** [adad184/MMPopupView#13]
Delpoyment Target: iOS 7.0
Base Target: iOS 9.0

Version: 1.5

[[[MMAlertView alloc] initWithConfirmTitle:@"xxxxxx" detail:nil] show];

Never show up

**Comment by beiguancyc** [comment]
同上。demo运行正常，pod 安装自己项目上从没出来过。9。0

**Comment by adad184** [comment]
please the new version   1.5.1
