### ISSUE TITLE
非常奇怪，用pod安装的绝对出不来对话框

### ISSUE THREAD

**Issue by beiguancyc** [adad184/MMPopupView#15]
以前可以用的，后来不行了。demo正常，新建项目pod安装，照样不行。

**Comment by adad184** [comment]
你好 请试一下1.5.1版

**Comment by bulolo** [comment]
使用 1.5.1,pod安装，同样出不来。用回1.0可以
代码如下
let a:MMPopupItem = MMItemMake("取消",MMItemType.Normal, nil)
                                let b:MMPopupItem = MMItemMake("呼叫", MMItemType.Highlight, { (Int) -> Void in
                                    UIApplication.sharedApplication().openURL(NSURL(string: "tel://0755-24443912371")!)
                                })
                                let items:NSArray = [a,b]
                                let alertView = MMAlertView(title: "立刻拨打？", detail: "0755-23914442371", items: items as [AnyObject])
                                alertView.show()

**Comment by adad184** [comment]
@bulolo  我刚在swift项目里用了1.5.1    copy你的代码是可以显示出来的啊.......

**Comment by bulolo** [comment]
@adad184 抱歉抱歉，我前天用的，还以为是1.5.1,才发现更新不久。已经没问题。

**Comment by beiguancyc** [comment]
@adad184 非常感谢，已经正常
