### ISSUE TITLE
在自定义view上添加一个uicollectionview点击事件冲突的了

### ISSUE THREAD

**Issue by jiangmingz** [adad184/MMPopupView#16]
这个方法不调用- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {

**Comment by adad184** [comment]
不要直接把view添加到UIScrollView上     添加到UIScrollView的superView上

**Comment by jiangmingz** [comment]
我提交了一个修改到你的项目，你看看修改了一行代码

**Comment by jiangmingz** [comment]
我没有在uiscrollview上添加，是直接在MMPopupView上添加一个UICollectionView，点击cell不起作用，是手势和点击事件冲突造成的，我添加了gesture.cancelsTouchesInView = NO;就可以的了。

**Comment by adad184** [comment]
哦  是这样  确实是有这个问题  多谢
