### ISSUE TITLE
touchWildToHide开启以后  actionsheet的按钮的点击事件都失效了

### ISSUE THREAD

**Issue by hongdong** [adad184/MMPopupView#18]
touchWildToHide开启以后  actionsheet的按钮的点击事件都失效了，挺严重的一个bug，希望大神有时间的话调整一下、真是一个好用的库

**Comment by adad184** [comment]
我看demo里  开启了touchWildToHide   没有失效啊?

**Comment by hongdong** [comment]
我也是运行你的demo，按钮点击立马松开的事件是失效的、只有点击以后不松开、移动，然后松开  才会触发按钮的点击事件，

**Comment by hongdong** [comment]
![2015-12-24 11_25_22](https://cloud.githubusercontent.com/assets/5499518/11988970/14a61c66-aa31-11e5-8802-07a5e03aaa5c.gif)

**Comment by adad184** [comment]
刚解决了这个问题 麻烦试试 1.5.3

**Comment by hongdong** [comment]
cool、thx
