### ISSUE TITLE
Pod 内找不到该资源

### ISSUE THREAD

**Issue by JimmyTM** [adad184/MMPopupView#20]
使用 pod 'MMPopupView'  安装失败。
发现Pod内搜索不到该资源。

>MacPro:~$ pod search MMpopupView
>[!] Unable to find a pod with name matching `MMpopupView'

![Problem](http://i8.tietuku.com/cc5590c75223fc60.png)

如果看到，请帮忙回复下，谢谢！😄

**Comment by adad184** [comment]
这个 应该是你网络的问题吧?

**Comment by JimmyTM** [comment]
0.0.. 我尝试了下  XLForm 和AFNetworking 都没问题。难道是我pod版本问题？

![Problem](http://i8.tietuku.com/1965f6d7decaa427.jpg)

**Comment by JimmyTM** [comment]
Pod的官网是有的，看来是我这边的问题，我再找找问题。
谢谢回复。😄
![Problem](http://i4.tietuku.com/1520945554cf98b1.png)
