### ISSUE TITLE
Sheet添加多行问题

### ISSUE THREAD

**Issue by HistoryZhang** [adad184/MMPopupView#3]
Sheet添加多行会超出屏幕，不支持滚动。

**Comment by adad184** [comment]
这个问题我也考虑过 不过我觉得这属于设计上的问题  如果有那么多个选项 用sheet是否合适? 
所以这里我就没有对这种极限情况进行处理了 

如果你有需要 可以自己继承MMPopupView来实现一个可以滚动的Sheet  :)
