### ISSUE TITLE
Sheet类型，出现键盘时有一部分会被挡住

### ISSUE THREAD

**Issue by lazybetrayer** [adad184/MMPopupView#32]
如下图，出现键盘时下边的button被挡住了。
<img width="947" alt="2016-06-03 11 21 03" src="https://cloud.githubusercontent.com/assets/4188244/15767737/4ba06840-297d-11e6-872b-14295b4ff3dd.png">

**Comment by adad184** [comment]
...我觉得sheet类 不太适合再做键盘类的输入  如果有需要的话 可以自定义.
