### ISSUE TITLE
在修改AlertView的ItemColor时, TitleColor同时被修改了

### ISSUE THREAD

**Issue by gq630960023** [adad184/MMPopupView#4]
我在修改AlertView的ItemColor时, TitleColor同时被修改了,我查看了代码, 发现了如下部分. 
这似乎是一个BUG, 我提交上来. 请确认一下.
<img width="546" alt="titlecoloredit" src="https://cloud.githubusercontent.com/assets/3872235/10451077/991b528e-71d0-11e5-8742-67e712ffb67d.png">

**Comment by adad184** [comment]
哈哈  是我写错了  应该是 config.titleColor     不好意思 马上改
