### ISSUE TITLE
连续弹窗两次，第二个弹窗不出现

### ISSUE THREAD

**Issue by yaochenfeng** [adad184/MMPopupView#69]
用模拟器和手机都出现

**Comment by iostalks** [comment]
和系统的 AlertController 一样，连续弹出两次框是不被允许的，必须先 hide，才能弹出下一个。

具体可以参考 MMPopupCategory.m 中 mm_showDimBackground 方法的实现。

**Comment by macRong** [comment]
我也遇到这个问题，已修[]( https://github.com/macRong/MMPopupView)

**Comment by macRong** [comment]
尽量不要用这个库，太二了，，，各种问题😅， 多个弹窗叠加，关闭一个，然后大bug就出来了

**Comment by macRong** [comment]
邮件已收到，
