### ISSUE TITLE
Unable to find a pod with name matching `MMPopupView'

### ISSUE THREAD

**Issue by litt1e-p** [adad184/MMPopupView#7]
pod search MMPopupView
[!] Unable to find a pod with name matching `MMPopupView'?
do I write wrong?

**Comment by adad184** [comment]
$ pod search MMPopupView

-> MMPopupView (1.3)
   Pop-up based view(e.g. AlertView SheetView), or you can easily customize for
   your own usage.
   pod 'MMPopupView', '~> 1.3'
   - Homepage: https://github.com/adad184/MMPopupView
   - Source:   https://github.com/adad184/MMPopupView.git
   - Versions: 1.3, 1.2, 1.1, 1.0 [master repo]

It's available :)

http://cocoapods.org/pods/MMPopupView

**Comment by litt1e-p** [comment]
my gem sources is http://ruby.taobao.org/, is this sources can not find MMPopupView ?

**Comment by adad184** [comment]
.. 应该不是淘宝源的问题  是不是cocoapod的源的问题?

**Comment by litt1e-p** [comment]
可以帮忙看看您的源是什么吗
$ gem sources -l

**Comment by adad184** [comment]
我明天去公司帮你看一下

**Comment by litt1e-p** [comment]
ok, 多谢

**Comment by litt1e-p** [comment]
已解决，是我cocapods太久
