### ISSUE TITLE
UITableView嵌入 MMPopupView中后必须长按UITableViewCell后UITableView中的didSelectRowAtIndexPath 方法才会执行

### ISSUE THREAD

**Issue by yaochangjun** [adad184/MMPopupView#9]
UITableView嵌入 MMPopupView中后必须长按UITableViewCell后UITableView中的didSelectRowAtIndexPath 方法才会执行

**Comment by yaochangjun** [comment]
暂解决方法：在UITableViewCell中添加一个UIButton来触发事件，可能是触发优先级的问题造成无法执行didSelectRowAtIndexPath

**Comment by adad184** [comment]
是这样的  UITableView也是UIScrollView  UIScrollView非常的特殊 直接把view添加UIScrollView会一些问题 所以不建议这样做  建议把attachedView设置为UITableView的superView.

**Comment by adad184** [comment]
我换了demo 你可以看下最新的demo

**Comment by tah1993** [comment]
我把 UITableView 嵌入 MMPopupView 中后，UITableView 没办法滑动了
